### ISSUE TITLE
get FME info activity returns 415 Unsupported Media Type error

### ISSUE THREAD

**Issue by jianingliu** [vertigis/workflow-activities-fme#45]
Hi team,

I'm getting a 415 Unsupported Media Type error when using the get FME info activity. I've dig into the code and found a "Content-Type: application/x-www-form-urlencoded" header has been added in the request (line 50 at https://github.com/vertigis/workflow-activities-fme/commit/90fef6ac9e0a6c857bb3ae05ea0e1f4be3ac5098#diff-f294c7c8541dceeadc1682d3423488918beee90117e33328e977eec7a33e330d).

I've tested it against a FME server with Postman, and can replicate the issue if I add "Content-Type: application/x-www-form-urlencoded" to the header.

I suggest to remove that Content-Type from the header as this shouldn't be required for this GET request anyway.

Thanks,
Johnny

**Comment by rcooney** [comment]
Thanks for the detailed report. That makes it really easy. The fix is now in a PR and should be available in a day or two.

If you need an immediate workaround you can use the **Use FME Service** activity and set the path to `info`.
